/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './zgwnu-bonita.module';
import * as i2 from './rest-api/zgwnu-bonita-config.service';
import * as i3 from './rest-api/zgwnu-bonita-urls';
import * as i4 from './authentication/zgwnu-bonita-authentication.service';
import * as i5 from '@angular/http';
import * as i6 from '@angular/router';
import * as i7 from './bpm/process/zgwnu-bonita-bpm-process.service';
import * as i8 from './bpm/case/zgwnu-bonita-bpm-case.service';
import * as i9 from './bpm/document/zgwnu-bonita-bpm-case-document.service';
import * as i10 from './bpm/data/zgwnu-bonita-bpm-data.service';
import * as i11 from './bpm/activity/zgwnu-bonita-bpm-activity.service';
import * as i12 from './bpm/task/zgwnu-bonita-bpm-task.service';
import * as i13 from './bpm/human-task/zgwnu-bonita-bpm-human-task.service';
import * as i14 from './bpm/user-task/zgwnu-bonita-bpm-user-task.service';
import * as i15 from './bdm/zgwnu-bonita-business-data.service';
import * as i16 from './file-upload/zgwnu-bonita-file-upload.service';
export const ZgwnuBonitaModuleNgFactory:i0.NgModuleFactory<i1.ZgwnuBonitaModule> = i0.ɵcmf(i1.ZgwnuBonitaModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.ZgwnuBonitaConfigService,i2.ZgwnuBonitaConfigService,[i3.ZgwnuBonitaUrls]),
          i0.ɵmpd(4608,i4.ZgwnuBonitaAuthenticationService,i4.ZgwnuBonitaAuthenticationService,
              [i2.ZgwnuBonitaConfigService,i5.Http,i6.Router]),i0.ɵmpd(4608,i7.ZgwnuBonitaBpmProcessService,
              i7.ZgwnuBonitaBpmProcessService,[i2.ZgwnuBonitaConfigService,i5.Http]),
          i0.ɵmpd(4608,i8.ZgwnuBonitaBpmCaseService,i8.ZgwnuBonitaBpmCaseService,[i2.ZgwnuBonitaConfigService,
              i5.Http]),i0.ɵmpd(4608,i9.ZgwnuBonitaBpmCaseDocumentService,i9.ZgwnuBonitaBpmCaseDocumentService,
              [i2.ZgwnuBonitaConfigService,i5.Http]),i0.ɵmpd(4608,i10.ZgwnuBonitaBpmDataService,
              i10.ZgwnuBonitaBpmDataService,[i2.ZgwnuBonitaConfigService,i5.Http]),
          i0.ɵmpd(4608,i11.ZgwnuBonitaBpmActivityService,i11.ZgwnuBonitaBpmActivityService,
              [i2.ZgwnuBonitaConfigService,i5.Http]),i0.ɵmpd(4608,i12.ZgwnuBonitaBpmTaskService,
              i12.ZgwnuBonitaBpmTaskService,[i2.ZgwnuBonitaConfigService,i5.Http]),
          i0.ɵmpd(4608,i13.ZgwnuBonitaBpmHumanTaskService,i13.ZgwnuBonitaBpmHumanTaskService,
              [i2.ZgwnuBonitaConfigService,i5.Http]),i0.ɵmpd(4608,i14.ZgwnuBonitaBpmUserTaskService,
              i14.ZgwnuBonitaBpmUserTaskService,[i2.ZgwnuBonitaConfigService,i5.Http]),
          i0.ɵmpd(4608,i15.ZgwnuBonitaBusinessDataService,i15.ZgwnuBonitaBusinessDataService,
              [i2.ZgwnuBonitaConfigService,i5.Http]),i0.ɵmpd(4608,i16.ZgwnuBonitaFileUploadService,
              i16.ZgwnuBonitaFileUploadService,[i2.ZgwnuBonitaConfigService,i5.Http]),
          i0.ɵmpd(512,i1.ZgwnuBonitaModule,i1.ZgwnuBonitaModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL29ubm8vRG9jdW1lbnRzL0dJVC9Aemd3bnUvbmctYm9uaXRhL3NyYy96Z3dudS1ib25pdGEubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL29ubm8vRG9jdW1lbnRzL0dJVC9Aemd3bnUvbmctYm9uaXRhL3NyYy96Z3dudS1ib25pdGEubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
